version: 2
jobs:

  # Build and push the IPMI Simulator docker image to DockerHub
  build-push:
    working_directory: ~/ipmi-simulator
    docker:
      - image: docker:17.11.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Dependencies
          command: |
            apk add --update --no-cache musl-dev make
      - run:
          name: Build Images
          command: |
            make build
      - run:
          name: Push Images
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PS}
            for tag in $(make tags); do
              docker push ${tag}
            done

workflows:
  version: 2
  build:
    jobs:
      - build-push:
          filters:
            branches:
              only:
                - master
